name: Main Branch Automated Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']
        poetry-version: ['1.7.0']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Run image
      uses: abatilo/actions-poetry@v2.1.4
      with:
        poetry-version: ${{ matrix.poetry-version }}

    - name: Run tests
      working-directory: tests/
      run: |
        python -m unittest
